"""empty message

Revision ID: 1a4516195ffc
Revises: 3f93ca22f74e
Create Date: 2024-12-19 04:56:43.549596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a4516195ffc'
down_revision = '3f93ca22f74e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=25), nullable=False),
    sa.Column('media_url', sa.String(length=150), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flyer_img_url', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('flyer_img_url')

    op.drop_table('event_media')
    # ### end Alembic commands ###
