"""empty message

Revision ID: 1d4f45b96165
Revises: 3d0bcbad3a4f
Create Date: 2024-12-12 05:21:28.519797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d4f45b96165'
down_revision = '3d0bcbad3a4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('user_first_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('user_last_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('user_city', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('user_state', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('user_country', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('user_role', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('user_date_of_birth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('user_genre', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_event_organizer', sa.Boolean(), nullable=True))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('is_event_organizer')
        batch_op.drop_column('is_admin')
        batch_op.drop_column('user_genre')
        batch_op.drop_column('user_date_of_birth')
        batch_op.drop_column('user_role')
        batch_op.drop_column('user_country')
        batch_op.drop_column('user_state')
        batch_op.drop_column('user_city')
        batch_op.drop_column('user_last_name')
        batch_op.drop_column('user_first_name')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
