"""empty message

Revision ID: 578c944390e6
Revises: dc81c6e75a9a
Create Date: 2024-12-13 21:42:04.803588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '578c944390e6'
down_revision = 'dc81c6e75a9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_state')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_state', sa.VARCHAR(length=25), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
