"""empty message

Revision ID: 699b3aa1a455
Revises: cd48ac2a34fb
Create Date: 2024-12-22 05:13:51.901938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '699b3aa1a455'
down_revision = 'cd48ac2a34fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_media', sa.String(length=25), nullable=False),
    sa.Column('contact_data', sa.String(length=150), nullable=False),
    sa.Column('contact_event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_info')
    # ### end Alembic commands ###
