"""empty message

<<<<<<<< HEAD:migrations/versions/969b6ea62e88_.py
Revision ID: 969b6ea62e88
Revises: 
Create Date: 2024-12-24 03:42:35.167004
========
Revision ID: 99088d10a796
Revises: 
Create Date: 2024-12-24 02:32:17.504597
>>>>>>>> development:migrations/versions/99088d10a796_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99088d10a796'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=250), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('user_city', sa.String(length=30), nullable=True),
    sa.Column('user_country', sa.String(length=25), nullable=True),
    sa.Column('user_role', sa.String(length=15), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('user_gender', sa.String(length=10), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('event_description', sa.String(length=300), nullable=False),
    sa.Column('organizer_user_id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_start_time', sa.Time(), nullable=False),
    sa.Column('event_duration', sa.Time(), nullable=True),
    sa.Column('ticket_price', sa.Float(), nullable=True),
    sa.Column('event_address', sa.String(length=80), nullable=False),
    sa.Column('event_city', sa.String(length=30), nullable=False),
    sa.Column('event_country', sa.String(length=25), nullable=False),
    sa.Column('event_category', sa.String(length=25), nullable=False),
    sa.Column('age_clasification', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('flyer_img_url', sa.String(length=150), nullable=False),
    sa.Column('event_reject_msg', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['organizer_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_media', sa.String(length=25), nullable=False),
    sa.Column('contact_data', sa.String(length=150), nullable=False),
    sa.Column('contact_event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=25), nullable=False),
    sa.Column('media_url', sa.String(length=150), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_media')
    op.drop_table('contact_info')
    op.drop_table('events')
    op.drop_table('user')
    # ### end Alembic commands ###
