"""empty message

Revision ID: b0ac642f0fb0
Revises: 
Create Date: 2024-12-16 21:08:06.833267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0ac642f0fb0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('event_description', sa.String(length=300), nullable=False),
    sa.Column('organizer_user_id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_start_time', sa.Time(), nullable=False),
    sa.Column('event_duration', sa.Time(), nullable=True),
    sa.Column('ticket_price', sa.Float(), nullable=True),
    sa.Column('event_address', sa.String(length=80), nullable=False),
    sa.Column('event_city', sa.String(length=30), nullable=False),
    sa.Column('event_country', sa.String(length=25), nullable=False),
    sa.Column('event_category', sa.String(length=25), nullable=False),
    sa.Column('age_clasification', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=250), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('user_city', sa.String(length=30), nullable=True),
    sa.Column('user_country', sa.String(length=25), nullable=True),
    sa.Column('user_role', sa.String(length=15), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('user_gender', sa.String(length=10), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_event_organizer', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('events')
    # ### end Alembic commands ###
