"""empty message

Revision ID: ef98813efaf5
Revises: 
Create Date: 2025-01-10 23:38:00.772329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef98813efaf5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=250), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('user_city', sa.String(length=30), nullable=True),
    sa.Column('user_country', sa.String(length=25), nullable=True),
    sa.Column('user_role', sa.String(length=15), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('user_gender', sa.String(length=10), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('event_description', sa.String(length=300), nullable=False),
    sa.Column('organizer_user_id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_start_time', sa.Time(), nullable=False),
    sa.Column('event_duration', sa.Time(), nullable=True),
    sa.Column('ticket_price', sa.Float(), nullable=True),
    sa.Column('event_address', sa.String(length=80), nullable=False),
    sa.Column('event_city', sa.String(length=30), nullable=False),
    sa.Column('event_country', sa.String(length=25), nullable=False),
    sa.Column('event_category', sa.String(length=25), nullable=False),
    sa.Column('age_classification', sa.String(length=20), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('flyer_img_url', sa.String(length=150), nullable=False),
    sa.Column('event_admin_msg', sa.String(length=250), nullable=True),
    sa.Column('favorite_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organizer_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_media', sa.String(length=25), nullable=False),
    sa.Column('contact_data', sa.String(length=150), nullable=False),
    sa.Column('contact_event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=25), nullable=False),
    sa.Column('media_url', sa.String(length=150), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('event_media')
    op.drop_table('contact_info')
    op.drop_table('events')
    op.drop_table('user')
    # ### end Alembic commands ###
